### ISSUE TITLE
PLugin is not added/shown with mautic-4.4.3

### ISSUE THREAD

**Issue by marc4s** [content-optimizer-gmbh/mautic-doi-plugin#10]
any ideas?
webserver permimssions are fine. 

mautic/bin/console mautic:plugins:reload
0 neue Plugins wurden installiert und 0 aktualisiert.
.

it is not listed via plugins and the drop down field is not extended.
I have switched from php8.0 to 7.4 without success.

server is nginx with php-fpm

**Comment by saschafoerster** [comment]
I have the same issue.

**Comment by sebastian-fahrenkrog** [comment]
Have you upload the directory JotaworksDoiBundle in the plugins folder in mautic?

**Comment by marc4s** [comment]
everything was correct with the plugin upload. foldername. content. permissions. but it was not showing up.
I could solve it by switching to composer. nothing else needed to be changed.

so you may check it without composer setup or adjust the documentation.

thank you.
btw: I had a typo. it was not working with 4.4.8 (4.4.3 not tested)

**Comment by sebastian-fahrenkrog** [comment]
@marc4s  Thank you for the feedback! 

There are 2 bugfixes currently in the testing for 4.4.8 
One user  mention that the plugin is not activated after update and send a pull request. maybe it is solved with that. 

We don't use the composer setup (and will not do in the future). Only the releases. But we are at the moment with 4.4.5

I will update my dev to 4.4.9 and test it.

**Comment by Robmobius** [comment]
Just watched the video you did with Joey on the DOI plugin. I have tried to install it on my latest mautic 4.4.9 

Loaded the file to the plugins folder and renamed it to JotaworksDoiBundle as per the instructions under your video on Joey's page. On your github page you don't mention the need to rename the file so I am not sure if renaming is correct?

Cleared cache and reloaded plugins but its not showing in my mautic under plugins. 

Before I knee jerk assume its' because 4.4.9 is not supported yet I wanted to check if I had installed it correctly. Can you give an estimate of when (if?) 4.4.9 might be supported?

**Comment by sebastian-fahrenkrog** [comment]
@Robmobius The doi plugin is one of our most important plugins. We will update it for any mautic version. Currently our customer base use 4.4.5 but I will do the update to 4.4.9 the next days and patch it. 

There are already some pending bugfixes for 4.4.9. So maybe this will already do it. Lets see.

**Comment by sebastian-fahrenkrog** [comment]
Guys I updates my dev instance to mautic 4.4.9 but I could not replicate the issue with the plugin :-( 
Plugin is showing under plugins and showing in the form action list. 

One bugfix reported from oscar is already online. Pull request from KreativeKrise is in our testing and will be released soon. 

@Robmobius 
So just to be super sure I update the readme for this plugin. 

Please make sure that you have: 

1) Download the zip, unzip it and you take the JotaworksDoiBundle directory (under /src) and upload it to the /plugins dir in mautic



2) You clear the mautic cache and you reload the plugin list.

**Comment by saschafoerster** [comment]
Now I was able to install the plugin correctly. I updated Mautic to 4.4.9, 
Copied to content of /src from the zip to 
.../mautic/docroot/plugins/JotaworksDoiBundle
refreshed the cache, clicked on "Install Plugins" and boom, it was there as expected. Now I am curious how it behaves, when updating mautic itself. Does it stay? But at least this issue is done. :)

**Comment by Robmobius** [comment]
As suspected I was installing it incorrectly. I can now see it in 4.4.9 and busy configuring / learning how it works. Thanks for the extra guidance.

**Comment by Robmobius** [comment]
On configuring the plugin you have a few optional fields but they have been set up as required so can't be left blank / empty.

Also

I see a new field Lead field alias for email (optional) (marked as required). What is the intended use?

**Comment by sebastian-fahrenkrog** [comment]
@saschafoerster  @Robmobius  Thank you guys for the feedback! Mautic Update should be working fine. 

@Robmobius 
>I see a new field Lead field alias for email (optional). What is the intended use?

Thanks for the bug report under: https://github.com/content-optimizer-gmbh/mautic-doi-plugin/issues/12
I just realized that I never add the code to use that config field and hardcoded a email_validate field. 

But regarding the intended use: 
That is a little bit complicate to explain but let me try to explain the why.

If you use a mautic form and connect the lead field email with a form field (like you normally do) there is a problem: 
As soon as you submit the form, mautic thinks you are the lead with the email you submitted (Try it by yourself. There are also other tricks to become a lead with the email lead field public updateable). 

So just imagine you wanted to build some thing like a registration process with a profile page with mautic. I would like this lead only identified with that email IF the email is validatet ( = doi email with secure link is clicked). Not in any case. 

The solution is: you add another custom field (email_validate) and you make the email field not public updatable. 

Then you use a config like this to copy the email_validate address to the email lead field AFTER successfull opt in: 

<img width="599" alt="Bildschirmfoto 2023-06-12 um 10 00 57" src="https://github.com/content-optimizer-gmbh/mautic-doi-plugin/assets/50595160/cb1ff8e1-5fad-4503-a902-22d45f97e75b">

Result: 
You can now be sure that the lead is really under control of this email address.

**Comment by sebastian-fahrenkrog** [comment]
I close this ticket because the install problem should be solved.

**Comment by devcomputer** [comment]
I git wget the ZIP, unzipped the main.zip to mautic-doi-plugin-main/ and mv JotaworksDoiBundle to /docroot/plugins/JotaworksDoiBundle and chown it all.

Mautic 4.4.9  on php7.4 without composer, cleared the cache, reloaded the apache, clicked install plugins and DOI still not showing up.

any suggestions?

**Comment by marcschh** [comment]
thats the same experience I had. Tried two times, both times the same.
My solution was to switch the mautic installation to composer without other changes. after the plugin was shown

**Comment by sebastian-fahrenkrog** [comment]
@devcomputer If you could provide me a ssh access to a mautic installation with that issue I could debug. At the moment I'm not able to replicate the issue on my side.

**Comment by devcomputer** [comment]
@sebastian-fahrenkrog thanks. i got it working. the memory limit kept it from showing. fixed now. looks good so far!  💝
php7.4mautic4.4.9 works.
